# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'htz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for htz
  pod 'SnapKit'
  pod 'Kingfisher'
#  pod 'Alamofire'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  
  pod 'Weibo_SDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'
  pod 'WechatOpenSDK'
  pod 'TencentOpenAPI-Unofficial'
  
  pod 'FreeStreamer'

  target 'htzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'htzUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
