# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'htz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for htz
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'htzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'htzUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
